### ISSUE TITLE
Nuget Package is targeting x86 instead of MSIL

### ISSUE THREAD

**Issue by f1ana** [pokitdok/pokitdok-csharp#18]
I'm trying to use v1.17.10 of the NuGet package and I'm currently unable to proceed because of how the project is targeted.
On a .NET 4.6.1 project, I get the following build warning which ultimately causes the project to fail on start:
`There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "pokitdok-csharp, Version=1.17.6562.23038, Culture=neutral, processorArchitecture=x86", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.`
I've also noticed that the package also lists NUnit and NuSpec as dependencies.  I'm assuming that this is not intentional or required for the library.

**Comment by corbinbs** [comment]
Hi @f1ana - I've also used some separate projects within the solution locally to run through different use cases with command line tools.   I appreciate it when client libraries work to minimize run time dependencies and would like to see the same for the PokitDok client libraries.   Do you have a recommended structure that you've seen work well elsewhere?   Maybe we make this happen and get a PR going for this issue...

**Comment by f1ana** [comment]
I typically have the tests in a separate project so that a dependency on NUnit wouldn't get picked up by any automated NuGet packing utilities.  I'm a little swamped right now but I might be able to submit a PR soon.

**Comment by f1ana** [comment]
Hi @corbinbs - I've put together #20 to address the following:
Package should now build to AnyCPU instead of x86
Package should no longer require NUnit and NuSpec
Separate unit test project (tested with my credentials).  I don't have access/pay for every PokitDok endpoint, but the ones that I do pay for passed so I'm confident enough that the separate project works.

**Comment by corbinbs** [comment]
Hi @f1ana - thanks for posting #20 up for review.
I should be able to help review that in the next day or so and will also see if I can get some other 👀 on it.   Thanks for the feedback/contribution to help make the C# client better!
