### ISSUE TITLE
AppRegistrations endpoint not implemented?

### ISSUE THREAD

**Issue by f1ana** [pokitdok/pokitdok-csharp#21]
Hello,

I was looking at utilizing AppRegistrations within an .NET MVC project and it does not appear that AppRegistrations is implemented in this library.  Could we get it added?
https://platform.pokitdok.com/documentation/v4/#app-registrations

Thanks,
Chris

**Comment by f1ana** [comment]
Added #22 to address this

**Comment by corbinbs** [comment]
Hi @f1ana - thanks for #22 !
That looks 👌 to me.   I still need a little more review time for #20 and then we should be able to get those PRs processed.

**Comment by corbinbs** [comment]
I merged #22 this evening.
Will work on a new pokitdok C# release in next day or so if would like to verify #18 and #21 are working for you via the prebuilt release, too.  

Thanks!

**Comment by f1ana** [comment]
Sounds good, thanks!

**Comment by corbinbs** [comment]
Hi @f1ana - https://www.nuget.org/packages/PokitDokPlatformClient/1.18.0 is now published based on these recent adjustments to the C# client if you'd like to reference it for any of your work.  

Thanks again for your contributions to the library!
